### ISSUE TITLE
Problems running probytes under OpenSUSE 42.1

### ISSUE THREAD

**Issue by acrolink** [serpent213/probytes#15]
Would you please give some information as how to run probytes under OpenSUSE.. I am having trouble running probytes under OpenSUSE since my system does not have these files (as described in the FreeBSD instructions): `. /etc/rc.subr` and `/etc/newsyslog.conf`

**Comment by serpent213** [comment]
A better start might be the [Ubuntu instructions](https://github.com/improper/probytes/blob/master/docs/installation-ubuntu-apache.md). But you will probably need to modify the init script. Unfortunately I don't know OpenSUSE; please let me know if you have any specific issues.
